//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aguinaldo
    {
        public int IDAguinaldo { get; set; }
        public int IDCedula { get; set; }
        public int Anno { get; set; }
        public double MontoAguinaldo { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
