//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionDesem
    {
        public int IDEvaluacion { get; set; }
        public int Empleado { get; set; }
        public System.DateTime FechaEva { get; set; }
        public string Pregunta1 { get; set; }
        public double Calificacion1 { get; set; }
        public string Pregunta2 { get; set; }
        public double Calificacion2 { get; set; }
        public string Pregunta3 { get; set; }
        public double Calificacion3 { get; set; }
        public string Pregunta4 { get; set; }
        public double Calificacion4 { get; set; }
        public string Pregunta5 { get; set; }
        public double Calificacion5 { get; set; }
        public double CalificacionFinal { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
