//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incapacidad
    {
        public int IDIncapacidad { get; set; }
        public int Empleado { get; set; }
        public int TipoIncapacidad { get; set; }
        public int Estado { get; set; }
        public double CantDias { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public double MontoEmpresa { get; set; }
        public double MontoInca { get; set; }
        public double MontoIncaTotal { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoIncapacidad TipoIncapacidad1 { get; set; }
    }
}
