//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public int IDLiquidacion { get; set; }
        public int Empleado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int Motivo { get; set; }
        public int Estado { get; set; }
        public double SalarioMensual { get; set; }
        public double PromedioDiaLaboral { get; set; }
        public double Cesantia { get; set; }
        public double Preaviso { get; set; }
        public double Aguinaldo { get; set; }
        public double Vacaciones { get; set; }
        public double MontoTotalLiq { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual MotivoLiq MotivoLiq { get; set; }
    }
}
