//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoLaboral
    {
        public int IDPermiso { get; set; }
        public int Empleado { get; set; }
        public int TipoPermiso { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public double CantDias { get; set; }
        public string Observacion { get; set; }
        public bool PagoObligatorio { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoPermiso TipoPermiso1 { get; set; }
    }
}
