//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int IDPlanilla { get; set; }
        public int Empleado { get; set; }
        public string Periodo { get; set; }
        public System.DateTime FechaPlanill { get; set; }
        public double Salario { get; set; }
        public double CCSS { get; set; }
        public double Renta { get; set; }
        public double MontoInca { get; set; }
        public double Total { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
