//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHQuercus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUsuario { get; set; }
        public string Contrasena { get; set; }
        public string Salt { get; set; }
        public int Rol { get; set; }
        public string ConfirContrasena { get; set; }

        public virtual TipoRol TipoRol { get; set; }
    }
}
